"""minor col update

Revision ID: 7932bfb947ef
Revises: 00e838fe7e23
Create Date: 2024-08-23 14:26:50.829013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7932bfb947ef'
down_revision: Union[str, None] = '00e838fe7e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('project', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('customer', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
