"""add customer table and relations

Revision ID: 1a7b97dad6eb
Revises: 5cc0f74eb959
Create Date: 2024-08-22 18:08:19.313486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7b97dad6eb'
down_revision: Union[str, None] = '5cc0f74eb959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=True)
    op.add_column('project', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('project', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.drop_constraint('project_project_name_key', 'project', type_='unique')
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    op.create_foreign_key(None, 'project', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project', 'project_name')
    op.add_column('user', sa.Column('project_id', sa.UUID(), nullable=True))
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_foreign_key(None, 'user', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.drop_column('user', 'project_id')
    op.add_column('project', sa.Column('project_name', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.create_unique_constraint('project_project_name_key', 'project', ['project_name'])
    op.drop_column('project', 'customer_id')
    op.drop_column('project', 'name')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
