"""add server-side uuid to proj and customer tables

Revision ID: 6e73eb90398f
Revises: 1a7b97dad6eb
Create Date: 2024-08-22 18:09:47.423341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e73eb90398f'
down_revision: Union[str, None] = '1a7b97dad6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
